<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>TRINDS</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">
  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">
  
  
  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Moderna - v2.0.0
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<body>

   <!-- ======= Header ======= -->
   <header id="header" class="fixed-top ">
	  <div class="container">

	    <div class="logo float-left">
            <a href="index.php"><img src="assets/img/logo.png" alt="logo"></a>      <!-- TRINDS logo-->            
            <!--<h1 class="text-light"><a href="index.php"><span>TRINDS</span></a></h1> !-->
	    </div>
	
	      <nav class="nav-menu float-right d-none d-lg-block"> <ul>
                <li><a href="index.php">Home</a></li>
		<li><a href="login_user.php">About Us</a></li>
                <li><a href="login_user.php">Map</a></li>
                <li><a href="login_user.php">Statistics</a></li>
                <li><a href="login_user.php">Contact Us</a></li>    
		<li class="drop-down"><a href="#">Login</a>
                    <ul>
                        <li><a href="login.php">Login as admin</a></li>
                        <li><a href="login_user.php">Login as user</a></li>
                    </ul> 
                </li>    
                 
              </nav><!-- .nav-menu -->

            </div>
    </header><!-- End Header -->

<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

