<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>TRINDS</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">
  
  
  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Moderna - v2.0.0
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<body>

   <!-- ======= Header ======= -->
   <header id="header" class="fixed-top ">


        <div class="container">

	<div class="logo float-left">
            <a href="index.php"><img src="assets/img/logo.png" alt="logo"></a>      <!-- TRINDS logo-->            
            <!--<h1 class="text-light"><a href="index.php"><span>TRINDS</span></a></h1> !-->
	</div>
	
        <!-- Start of nav-menu -->
        <nav class="nav-menu float-right d-none d-lg-block"> <ul>
            <li class="drop-down"><a href="welcome_user.php">Home</a>
                <ul>
		    <li><a href="about_user.php">About Us</a></li>
                </ul>

		  </li>
		  <li><a href="map_user.php">Map</a></li>

          <li class="drop-down"><a href="#">Statistics</a>
                <ul>
                  <li><a href="overall_user.php">Overall</a></li>
                  <li><a href="accidents_user.php">Accidents</a></li>
                  <li><a href="breakdown_user.php">Breakdowns</a></li>
                  <li><a href="roadworks_user.php">Road Works</a></li>
                  <li><a href="heavytraffic_user.php">Heavy Traffic</a></li>
                  <li><a href="roadclosures_user.php">Road closures</a></li>
                </ul>
		  </li>		
             
          <li class="drop-down"><a href="contact_user.php">Contact Us</a>

		 <ul>
                    <li><a href="faq_user.php">FAQ</a></li>
                    <li><a href="entry.php">Submit Entry</a></li>
                 </ul>
          </li>	   
          <li><a href="logout_user.php">Logout</a></li>
      </nav>    <!--End of nav-menu -->

    </div>
  </header>     <!-- End Header -->
  
</body>

