<!-- ======= Footer ======= -->
<footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
                <h4>Useful Links</h4>
                <ul>
                    <li><i class="bx bx-chevron-right"></i> <a href="index.php">Home</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="about.php">About us</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="map.php">Map</a></li>
                    <li><i class="bx bx-chevron-right"></i> <a href="entry-part1.php">Submit Entry</a></li>
                </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
                <h4>Contact Us</h4>
                    <p>
                        10 Dover Dr <br>
                        Singapore 138683<br>
                        <strong>Phone:</strong> +65 6592 1189<br>
                        <strong>Email:</strong> singaporetech.edu.sg<br>
                    </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-info">
                <h3>About TRINDS</h3>
                    <p>TRINDS is a service platform where users are updated on the latest traffic news on the road.</p>
                    <p>Going out today? Use TRINDS!</p>
		<div class="social-links mt-3">
                <a href="https://www.facebook.com/SingaporeTech/" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="https://www.instagram.com/singaporetech/" class="instagram"><i class="bx bxl-instagram"></i></a>
                </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Moderna</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        <br />
        Created my free logo at <a href="https://logomakr.com/">LogoMakr.com</a>
      </div>
    </div>
    
</footer>   <!-- End Footer -->

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>
