<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>TRINDS</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">
  
  
  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Moderna - v2.0.0
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<body>

   <!-- ======= Header ======= -->
   <header id="header" class="fixed-top ">
	  <div class="container">

	    <div class="logo float-left">
            <h1 class="text-light"><a href="webpage.html"><span>TRINDS</span></a></h1>
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
	    </div>
	
	      <nav class="nav-menu float-right d-none d-lg-block"> <ul>
          <li class="drop-down"><a href="webpage.html">Home</a>
		  <ul>
		    <li><a href="about.html">About Us</a></li>
          </ul>
		  </li>
		  <li><a href="map.php">Map</a></li>
          <li class="drop-down"><a href="#">Statistics</a>
                <ul>
                  <li><a href="#">Overall</a></li>
                  <li><a href="#">Accidents</a></li>
                  <li><a href="#">Breakdowns</a></li>
                  <li><a href="#">Road Works</a></li>
                  <li><a href="#">Heavy Traffic</a></li>
                  <li><a href="#">Road closures</a></li>
                </ul>
		  </li>		
             
          <li class="drop-down"><a href="#">Contact Us</a>
		       <ul>
				 <li><a href="faq.php">FAQ</a></li>
				 <li><a href="entry-part1.php">Submit Entry</a></li>
               </ul>
		  </li>	   
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->
  

<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

